name: Canary Release

on: push
  # pull_request:
  #   branches:
  #     - master
  #   types:
  #     - closed

jobs:
  test:
    name: Deploy
    runs-on: ubuntu-latest
    # if: github.event.pull_request.merged
    env:
      NODE_AUTH_TOKEN: ${{secrets.WOMBOT_NPM_TOKEN}}

    steps:
    - uses: actions/checkout@v1
    - name: Set up Node (10)
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
        registry-url: 'https://wombat-dressing-room.appspot.com/firebase/_ns/'
    # - name: Yarn install
    #   run: yarn
    # - name: yarn build
    #   run: yarn build
    - name: Deploy canary
      run: |
        npm config ls
        cat /home/runner/work/_temp/.npmrc
        npm --registry https://wombat-dressing-room.appspot.com/firebase/_ns/ whoami
        yarn release --canary
      env:
        CI: true
