name: Run All Tests

on: push
# on: 
#   pull_request:
#     branches:
#       - master
#     types:
#       - closed
#   schedule:
#     - cron: '0 6,18 * * *'

jobs:
  # test:
  #   name: Node.js and Browser (Chrome) Tests
  #   runs-on: ubuntu-latest

  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Set up Node (10)
  #     uses: actions/setup-node@v1
  #     with:
  #       node-version: 10.x
  #   - name: install Chrome stable
  #     run: |
  #       sudo apt-get update
  #       sudo apt-get install google-chrome-stable
  #   - name: Test setup and yarn install
  #     run: |
  #       cp config/ci.config.json config/project.json
  #       yarn
  #   - name: yarn build
  #     run: yarn build
  #   - name: Run unit tests
  #     run: xvfb-run yarn test
  #   - name: Generate coverage file
  #     run: yarn ci:coverage
  #   - name: Run coverage
  #     uses: coverallsapp/github-action@master
  #     with:
  #       github-token: ${{ secrets.GITHUB_TOKEN }}
  #       path-to-lcov: ./lcov-all.info
  #     continue-on-error: true
  deploy:
    name: Canary Deploy
    runs-on: ubuntu-latest
    # if: github.event.pull_request.merged
    # needs: test

    steps:
    - uses: actions/checkout@v2
    - name: Checkout
      # Canary release script requires git history and tags.
      run: git fetch --prune --unshallow
    - name: Set up Node (10)
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: Yarn install
      run: yarn
    - name: Deploy canary
      run: yarn release --canary
      env:
        NPM_TOKEN_FIREBASE: ${{secrets.NPM_TOKEN_FIREBASE}}
        NPM_TOKEN_ANALYTICS: ${{secrets.NPM_TOKEN_ANALYTICS}}
        NPM_TOKEN_APP_TYPES: ${{secrets.NPM_TOKEN_APP_TYPES}}
        NPM_TOKEN_UTIL: ${{secrets.NPM_TOKEN_UTIL}}
        CI: true
