name: Run All Tests

on: push
# on: 
#   pull_request:
#     branches:
#       - master
#     types:
#       - closed
#   schedule:
#     - cron: '0 6,18 * * *'

jobs:
  # test:
  #   name: Node.js and Browser (Chrome) Tests
  #   runs-on: ubuntu-latest

  #   steps:
  #   - uses: actions/checkout@v2
  #   - name: Set up Node (10)
  #     uses: actions/setup-node@v1
  #     with:
  #       node-version: 10.x
  #   - name: install Chrome stable
  #     run: |
  #       sudo apt-get update
  #       sudo apt-get install google-chrome-stable
  #   - name: Test setup and yarn install
  #     run: |
  #       cp config/ci.config.json config/project.json
  #       yarn
  #   - name: yarn build
  #     run: yarn build
  #   - name: Run unit tests
  #     run: xvfb-run yarn test
  #   - name: Generate coverage file
  #     run: yarn ci:coverage
  #   - name: Run coverage
  #     uses: coverallsapp/github-action@master
  #     with:
  #       github-token: ${{ secrets.GITHUB_TOKEN }}
  #       path-to-lcov: ./lcov-all.info
  #     continue-on-error: true
  deploy:
    name: Canary Deploy
    runs-on: ubuntu-latest
    # if: github.event.pull_request.merged
    # needs: test

    steps:
    - uses: actions/checkout@v2
    - name: Checkout
      run: git fetch --prune --unshallow
    - name: Set up Node (10)
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: Yarn install
      run: yarn
    # - name: Yarn build
    #   run: yarn build
    - name: Deploy canary
      run: |
        echo "//wombat-dressing-room.appspot.com/@firebase/app-types/_ns:_authToken=$NPM_TOKEN_APP_TYPES" >> ~/.npmrc
        echo "//wombat-dressing-room.appspot.com/@firebase/app-types/_ns/:_authToken=$NPM_TOKEN_APP_TYPES" >> ~/.npmrc
        cat ~/.npmrc
        sed -i "s/\"version\": \"\([^\"]*\)\"/\"version\": \"\1-canary.$(git rev-parse --short HEAD)\"/g" packages/app-types/package.json
        npm publish --cwd packages/app-types --tag canary --registry https://wombat-dressing-room.appspot.com/@firebase/app-types/_ns
      # run: |
      #   echo "//wombat-dressing-room.appspot.com/@firebase/app-types/_ns/:_authToken=$NPM_TOKEN_APP_TYPES" >> ~/.npmrc
      #   yarn release --canary
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN_APP_TYPES}}
        NPM_AUTH_TOKEN: ${{secrets.NPM_TOKEN_APP_TYPES}}
        NPM_TOKEN: ${{secrets.NPM_TOKEN_APP_TYPES}}
        NPM_TOKEN_APP_TYPES: ${{secrets.NPM_TOKEN_APP_TYPES}}
        CI: true
      # env:
      #   NPM_TOKEN_FIREBASE: ${{secrets.NPM_TOKEN_FIREBASE}}
      #   NPM_TOKEN_ANALYTICS: ${{secrets.NPM_TOKEN_ANALYTICS}}
      #   NPM_TOKEN_APP_TYPES: ${{secrets.NPM_TOKEN_APP_TYPES}}
      #   CI: true
